project:
  type: website
  output-dir: _site

website:
  title: "Risyad Abiyyu Siregar"
  google-analytics: "G-2BCRMN1T6G"
  navbar:
    background: light
    foreground: dark
    left:
      - href: thoughts.qmd
        text: Thoughts
      - href: index.qmd
        text: About
      - href: contact.qmd
        text: Contact
  page-footer:
    left:
      - icon: envelope
        href: "mailto:abiyyusiregar@gmail.com"
      - icon: linkedin
        href: "https://www.linkedin.com/in/abiyyusiregar/"
      - icon: github
        href: "https://github.com/rasiregar"
    center: "Risyad Abiyyu Siregar &middot; 2026 &copy; All rights reserved."
    background: light

format:
  html:
    theme:
      - flatly
      - custom.scss
    toc: false
    link-external-newwindow: true
    smooth-scroll: true
