---
title: "Merdeka?"
author: Risyad Abiyyu Siregar
date: 2026-08-17
description: "Renungan kemerdekaan"
---

"Merdeka! Merdeka! Merdeka!"

Begitulah seruan para pahlawan pendahulu kita. Agustus 1945, penantian beratus tahun dari bangsa yang lama dibelenggu penjajahan. Cukup sudah diinjak, dipermalukan, dianaktirikan di tanah air sendiri. Yang muda, yang tua, semua yang terjajah di hindia belanda dengan bulat menyatakan kemerdekaannya.

Tanda seru dari "Merdeka!" bermakna teriakan, suar semangat perjuangan. Bentuknya lurus seperti cita-cita bersama para pendiri bangsa, akan mimpi kedaulatan dan koeksistensi di antara bangsa-bangsa lain di dunia. Tegak, layaknya hukum yang dicita-citakan bagi seluruh rakyatnya.

---

Jika ada pelajaran yang dapat dipetik dari delapan puluh satu tahun terakhir, ialah kemerdekaan itu perlu diperjuangkan setiap harinya. Proklamasi di Pegangsaan Timur oleh Ir. Soekarno hanyalah deklarasi. Setiap hari sejak itu, kita harus mempertahankan kemerdekaan itu dan cita-cita yang menyertai.

Proses yang dilewati tidaklah mudah. Ancaman datang silih berganti sejak proklamasi. Dari luar, ada agresi militer Belanda, pergumulan pasukan Sekutu, hingga blokade diplomatik dari negara post-kolonial. Pertempuran dan perundingan pun berlangsung tahun demi tahun agar bendera merah putih tetap berkibar. Sebut saja Ambarawa, Surabaya, Medan Area, dan Yogyakarta. Linggajati, Kapal USS Renville, hingga Meja Bundar di Den Haag.

Dari dalam, beragam tokoh yang awalnya ikut dalam perlawanan melawan ancaman luar memutuskan untuk membelot dari republik. PKI Madiun, PRRI, Permesta, Darul Islam. Gejolak datang ketika arah bangsa tidak disepakati oleh orang-orang yang memperjuangkannya.

Negara ini juga mengakhiri millenium dengan menumpas otokrasi dan militerisme. Reformasi menggulingkan orde baru, berikut korupsi, kolusi, dan nepotisme. Demi supremasi sipil dan kedaulatan hukum. Nyawa melayang, badan terluka, dan rumah terbakar dalam memperjuangkan negara yang sebenarnya sudah merdeka.

Merdeka adalah perjuangan kita setiap hari.

Nyaris tiga dekade sejak rakyat menduduki rumahnya di Senayan, terbesit dari pikiranku apakah kita sudah cukup berjuang? Apakah kita sudah merdeka?

Merdeka dari siapa?

Merdeka diterjemahkan dalam bahasa Inggris menjadi _independence_, yang berarti tidak bergantung. Berdikari.

Lucu bahwa istilah _independence_ dipakai di berbagai bidang, terutama riset, untuk menggambarkan sesuatu yang bebas pengaruh atas elemen lainnya. Kalau memang secara etimologi makna independensi seperti itu, apakah kita sudah "tidak bergantung" dan "bebas pengaruh"? Sementara negara melalui institusinya sibuk mempengaruhi dan menciptakan ketergantungan pada rakyatnya.

Tegaknya garis pada tanda seru semakin bengkok, atas arah gerak bangsa yang semakin tersesat. Para pemimpin negeri menunjukkan keteladanan yang buruk. Tata kelola pemerintahan yang semakin diinfestasi tikus-tikus. Kapitalisme kroni yang hanya menguntungkan segelintir elit dan menderitakan ratusan juta jiwa lainnya.

Semua asal bapak senang. Penjilatan berjamaah hilir ke hulu. Hingga basah, hingga ego rapuhnya tervalidasi. Pagi ini di upacara ke-Merdeka!-an, foto raksasa sang Kepala Negara dikibarkan melalui tim pasukan terjun bebas. Diskon transportasi umum yang tadinya 1 Rupiah menjadi 8 Rupiah, angka kesukaan Beliau. Gestur yang tidak berbahaya, cenderung remeh bahkan, cuma menggelitik akal pikiran kita bersama: "Republik ini punya siapa?" 

Tanda seru yang tajam seperti parang Pattimura pun semakin tumpul. Metafora atas kedaulatan hukum yang semakin tumpul ke atas, tajam ke bawah. Kekuasaan yang seharusnya dimandatkan oleh rakyat untuk rakyat, dijadikan alat kontrol dan subversi oleh para pemegang senjata. Militer merambah ke sipil. Suara keresahan rakyat dianggap 'hujatan'. Kritik dibalas _nye-nye-nye-nye_. Sistem peradilan dibuat untuk memihak kepada pemegang kuasa. Bagaimana menilai kualitas sistem peradilan kita? Lihatlah Wakil Presiden kita.

Tanda seru yang semakin bengkok, lama-lama menjadi tanda tanya. Yang tadinya seruan semangat, menjadi tanya kebingungan.

"Merdeka!" atau "Merdeka?"


